### GET request api clientes
GET {{host}}/clientes
Accept: application/json

### GET request cliente {id}
GET {{host}}/clientes/2
Accept: application/json

### GET request cliente {id} no existe
GET {{host}}/clientes/100
Accept: application/json

### Send POST request with json body
POST {{host}}/clientes
Content-Type: application/json

{
  "nombre": "Hola",
  "apellido": "otro",
  "email": "jperez1@yahoo.com"
}

### Send PUT request with json body
PUT {{host}}/clientes/2
Content-Type: application/json

{
  "nombre": "actualiza",
  "apellido": "actualiza",
  "email": "jperez1@yahoo.com"
}

### Send DELETE request with id
DELETE {{host}}/clientes/2
