# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/bionic64"
    web.vm.network "private_network", ip: "192.168.20.11"
    
    web.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
    end
    
    web.vm.provision "shell", inline: <<-SHELL
      apt update
      apt install apache2 git -y
      systemctl start apache2
      systemctl enable apache2
      cd /tmp/
      git clone https://github.com/NestorMonroy/2135_mini_finance
      cp -r 2135_mini_finance/* /var/www/html/
      systemctl restart apache2
    SHELL
  end

  config.vm.define "db" do |db|
    db.vm.box = "centos/7"
    db.vm.network "private_network", ip: "192.168.20.12"
    
    db.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
    end
    
    db.vm.provision "shell", inline: <<-SHELL
      yum install mariadb-server -y
      systemctl start mariadb
      systemctl enable mariadb

      mysql -u root -e 'CREATE DATABASE dbmini;'
      mysql -u root -e 'GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER ON dbmini.* TO dbmini@localhost IDENTIFIED BY "admin123";'
      mysql -u root -e 'FLUSH PRIVILEGES;'
    SHELL
  end

end
